-- ----------------------------
-- Records of tinhthanhpho
-- ----------------------------
INSERT INTO tinhthanhpho VALUES ('01', N'Thành phố Hà Nội', N'Thành phố Trung ương');
INSERT INTO tinhthanhpho VALUES ('02', N'Tỉnh Hà Giang', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('04', N'Tỉnh Cao Bằng', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('06', N'Tỉnh Bắc Kạn', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('08', N'Tỉnh Tuyên Quang', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('10', N'Tỉnh Lào Cai', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('11', N'Tỉnh Điện Biên', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('12', N'Tỉnh Lai Châu', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('14', N'Tỉnh Sơn La', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('15', N'Tỉnh Yên Bái', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('17', N'Tỉnh Hoà Bình', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('19', N'Tỉnh Thái Nguyên', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('20', N'Tỉnh Lạng Sơn', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('22', N'Tỉnh Quảng Ninh', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('24', N'Tỉnh Bắc Giang', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('25', N'Tỉnh Phú Thọ', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('26', N'Tỉnh Vĩnh Phúc', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('27', N'Tỉnh Bắc Ninh', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('30', N'Tỉnh Hải Dương', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('31', N'Thành phố Hải Phòng', N'Thành phố Trung ương');
INSERT INTO tinhthanhpho VALUES ('33', N'Tỉnh Hưng Yên', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('34', N'Tỉnh Thái Bình', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('35', N'Tỉnh Hà Nam', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('36', N'Tỉnh Nam Định', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('37', N'Tỉnh Ninh Bình', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('38', N'Tỉnh Thanh Hóa', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('40', N'Tỉnh Nghệ An', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('42', N'Tỉnh Hà Tĩnh', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('44', N'Tỉnh Quảng Bình', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('45', N'Tỉnh Quảng Trị', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('46', N'Tỉnh Thừa Thiên Huế', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('48', N'Thành phố Đà Nẵng', N'Thành phố Trung ương');
INSERT INTO tinhthanhpho VALUES ('49', N'Tỉnh Quảng Nam', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('51', N'Tỉnh Quảng Ngãi', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('52', N'Tỉnh Bình Định', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('54', N'Tỉnh Phú Yên', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('56', N'Tỉnh Khánh Hòa', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('58', N'Tỉnh Ninh Thuận', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('60', N'Tỉnh Bình Thuận', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('62', N'Tỉnh Kon Tum', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('64', N'Tỉnh Gia Lai', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('66', N'Tỉnh Đắk Lắk', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('67', N'Tỉnh Đắk Nông', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('68', N'Tỉnh Lâm Đồng', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('70', N'Tỉnh Bình Phước', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('72', N'Tỉnh Tây Ninh', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('74', N'Tỉnh Bình Dương', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('75', N'Tỉnh Đồng Nai', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('77', N'Tỉnh Bà Rịa - Vũng Tàu', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('79', N'Thành phố Hồ Chí Minh', N'Thành phố Trung ương');
INSERT INTO tinhthanhpho VALUES ('80', N'Tỉnh Long An', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('82', N'Tỉnh Tiền Giang', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('83', N'Tỉnh Bến Tre', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('84', N'Tỉnh Trà Vinh', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('86', N'Tỉnh Vĩnh Long', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('87', N'Tỉnh Đồng Tháp', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('89', N'Tỉnh An Giang', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('91', N'Tỉnh Kiên Giang', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('92', N'Thành phố Cần Thơ', N'Thành phố Trung ương');
INSERT INTO tinhthanhpho VALUES ('93', N'Tỉnh Hậu Giang', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('94', N'Tỉnh Sóc Trăng', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('95', N'Tỉnh Bạc Liêu', N'Tỉnh');
INSERT INTO tinhthanhpho VALUES ('96', N'Tỉnh Cà Mau', N'Tỉnh');


-- ----------------------------
-- Records of quanhuyen
-- --------------------------N
INSERT INTO quanhuyen VALUES ('002', N'Quận Hoàn Kiếm',  N'Quận', '01');
INSERT INTO quanhuyen VALUES ('003', N'Quận Tây Hồ',     N'Quận', '01');
INSERT INTO quanhuyen VALUES ('004', N'Quận Long Biên',  N'Quận', '01');
INSERT INTO quanhuyen VALUES ('001', N'Quận Ba Đình',    N'Quận', '01');
INSERT INTO quanhuyen VALUES ('005', N'Quận Cầu Giấy', N'Quận', '01');
INSERT INTO quanhuyen VALUES ('006', N'Quận Đống Đa', N'Quận', '01');
INSERT INTO quanhuyen VALUES ('007', N'Quận Hai Bà Trưng', N'Quận', '01');
INSERT INTO quanhuyen VALUES ('008', N'Quận Hoàng Mai', N'Quận', '01');
INSERT INTO quanhuyen VALUES ('009', N'Quận Thanh Xuân', N'Quận', '01');
INSERT INTO quanhuyen VALUES ('016', N'Huyện Sóc Sơn', N'Huyện', '01');
INSERT INTO quanhuyen VALUES ('017', N'Huyện Đông Anh', N'Huyện', '01');
INSERT INTO quanhuyen VALUES ('018', N'Huyện Gia Lâm', N'Huyện', '01');
INSERT INTO quanhuyen VALUES ('019', N'Quận Nam Từ Liêm', N'Quận', '01');
INSERT INTO quanhuyen VALUES ('020', N'Huyện Thanh Trì', N'Huyện', '01');
INSERT INTO quanhuyen VALUES ('021', N'Quận Bắc Từ Liêm', N'Quận', '01');
INSERT INTO quanhuyen VALUES ('024', N'Thành phố Hà Giang', N'Thành phố', '02');
INSERT INTO quanhuyen VALUES ('026', N'Huyện Đồng Văn', N'Huyện', '02');
INSERT INTO quanhuyen VALUES ('027', N'Huyện Mèo Vạc', N'Huyện', '02');
INSERT INTO quanhuyen VALUES ('028', N'Huyện Yên Minh', N'Huyện', '02');
INSERT INTO quanhuyen VALUES ('029', N'Huyện Quản Bạ', N'Huyện', '02');
INSERT INTO quanhuyen VALUES ('030', N'Huyện Vị Xuyên', N'Huyện', '02');
INSERT INTO quanhuyen VALUES ('031', N'Huyện Bắc Mê', N'Huyện', '02');
INSERT INTO quanhuyen VALUES ('032', N'Huyện Hoàng Su Phì', N'Huyện', '02');
INSERT INTO quanhuyen VALUES ('033', N'Huyện Xín Mần', N'Huyện', '02');
INSERT INTO quanhuyen VALUES ('034', N'Huyện Bắc Quang', N'Huyện', '02');
INSERT INTO quanhuyen VALUES ('035', N'Huyện Quang Bình', N'Huyện', '02');
INSERT INTO quanhuyen VALUES ('040', N'Thành phố Cao Bằng', N'Thành phố', '04');
INSERT INTO quanhuyen VALUES ('042', N'Huyện Bảo Lâm', N'Huyện', '04');
INSERT INTO quanhuyen VALUES ('043', N'Huyện Bảo Lạc', N'Huyện', '04');
INSERT INTO quanhuyen VALUES ('044', N'Huyện Thông Nông', N'Huyện', '04');
INSERT INTO quanhuyen VALUES ('045', N'Huyện Hà Quảng', N'Huyện', '04');
INSERT INTO quanhuyen VALUES ('046', N'Huyện Trà Lĩnh', N'Huyện', '04');
INSERT INTO quanhuyen VALUES ('047', N'Huyện Trùng Khánh', N'Huyện', '04');
INSERT INTO quanhuyen VALUES ('048', N'Huyện Hạ Lang', N'Huyện', '04');
INSERT INTO quanhuyen VALUES ('049', N'Huyện Quảng Uyên', N'Huyện', '04');
INSERT INTO quanhuyen VALUES ('050', N'Huyện Phục Hoà', N'Huyện', '04');
INSERT INTO quanhuyen VALUES ('051', N'Huyện Hoà An', N'Huyện', '04');
INSERT INTO quanhuyen VALUES ('052', N'Huyện Nguyên Bình', N'Huyện', '04');
INSERT INTO quanhuyen VALUES ('053', N'Huyện Thạch An', N'Huyện', '04');
INSERT INTO quanhuyen VALUES ('058', N'Thành Phố Bắc Kạn', N'Thành phố', '06');
INSERT INTO quanhuyen VALUES ('060', N'Huyện Pác Nặm', N'Huyện', '06');
INSERT INTO quanhuyen VALUES ('061', N'Huyện Ba Bể', N'Huyện', '06');
INSERT INTO quanhuyen VALUES ('062', N'Huyện Ngân Sơn', N'Huyện', '06');
INSERT INTO quanhuyen VALUES ('063', N'Huyện Bạch Thông', N'Huyện', '06');
INSERT INTO quanhuyen VALUES ('064', N'Huyện Chợ Đồn', N'Huyện', '06');
INSERT INTO quanhuyen VALUES ('065', N'Huyện Chợ Mới', N'Huyện', '06');
INSERT INTO quanhuyen VALUES ('066', N'Huyện Na Rì', N'Huyện', '06');
INSERT INTO quanhuyen VALUES ('070', N'Thành phố Tuyên Quang', N'Thành phố', '08');
INSERT INTO quanhuyen VALUES ('071', N'Huyện Lâm Bình', N'Huyện', '08');
INSERT INTO quanhuyen VALUES ('072', N'Huyện Nà Hang', N'Huyện', '08');
INSERT INTO quanhuyen VALUES ('073', N'Huyện Chiêm Hóa', N'Huyện', '08');
INSERT INTO quanhuyen VALUES ('074', N'Huyện Hàm Yên', N'Huyện', '08');
INSERT INTO quanhuyen VALUES ('075', N'Huyện Yên Sơn', N'Huyện', '08');
INSERT INTO quanhuyen VALUES ('076', N'Huyện Sơn Dương', N'Huyện', '08');
INSERT INTO quanhuyen VALUES ('080', N'Thành phố Lào Cai', N'Thành phố', '10');
INSERT INTO quanhuyen VALUES ('082', N'Huyện Bát Xát', N'Huyện', '10');
INSERT INTO quanhuyen VALUES ('083', N'Huyện Mường Khương', N'Huyện', '10');
INSERT INTO quanhuyen VALUES ('084', N'Huyện Si Ma Cai', N'Huyện', '10');
INSERT INTO quanhuyen VALUES ('085', N'Huyện Bắc Hà', N'Huyện', '10');
INSERT INTO quanhuyen VALUES ('086', N'Huyện Bảo Thắng', N'Huyện', '10');
INSERT INTO quanhuyen VALUES ('087', N'Huyện Bảo Yên', N'Huyện', '10');
INSERT INTO quanhuyen VALUES ('088', N'Huyện Sa Pa', N'Huyện', '10');
INSERT INTO quanhuyen VALUES ('089', N'Huyện Văn Bàn', N'Huyện', '10');
INSERT INTO quanhuyen VALUES ('094', N'Thành phố Điện Biên Phủ', N'Thành phố', '11');
INSERT INTO quanhuyen VALUES ('095', N'Thị Xã Mường Lay', N'Thị xã', '11');
INSERT INTO quanhuyen VALUES ('096', N'Huyện Mường Nhé', N'Huyện', '11');
INSERT INTO quanhuyen VALUES ('097', N'Huyện Mường Chà', N'Huyện', '11');
INSERT INTO quanhuyen VALUES ('098', N'Huyện Tủa Chùa', N'Huyện', '11');
INSERT INTO quanhuyen VALUES ('099', N'Huyện Tuần Giáo', N'Huyện', '11');
INSERT INTO quanhuyen VALUES ('100', N'Huyện Điện Biên', N'Huyện', '11');
INSERT INTO quanhuyen VALUES ('101', N'Huyện Điện Biên Đông', N'Huyện', '11');
INSERT INTO quanhuyen VALUES ('102', N'Huyện Mường Ảng', N'Huyện', '11');
INSERT INTO quanhuyen VALUES ('103', N'Huyện Nậm Pồ', N'Huyện', '11');
INSERT INTO quanhuyen VALUES ('105', N'Thành phố Lai Châu', N'Thành phố', '12');
INSERT INTO quanhuyen VALUES ('106', N'Huyện Tam Đường', N'Huyện', '12');
INSERT INTO quanhuyen VALUES ('107', N'Huyện Mường Tè', N'Huyện', '12');
INSERT INTO quanhuyen VALUES ('108', N'Huyện Sìn Hồ', N'Huyện', '12');
INSERT INTO quanhuyen VALUES ('109', N'Huyện Phong Thổ', N'Huyện', '12');
INSERT INTO quanhuyen VALUES ('110', N'Huyện Than Uyên', N'Huyện', '12');
INSERT INTO quanhuyen VALUES ('111', N'Huyện Tân Uyên', N'Huyện', '12');
INSERT INTO quanhuyen VALUES ('112', N'Huyện Nậm Nhùn', N'Huyện', '12');
INSERT INTO quanhuyen VALUES ('116', N'Thành phố Sơn La', N'Thành phố', '14');
INSERT INTO quanhuyen VALUES ('118', N'Huyện Quỳnh Nhai', N'Huyện', '14');
INSERT INTO quanhuyen VALUES ('119', N'Huyện Thuận Châu', N'Huyện', '14');
INSERT INTO quanhuyen VALUES ('120', N'Huyện Mường La', N'Huyện', '14');
INSERT INTO quanhuyen VALUES ('121', N'Huyện Bắc Yên', N'Huyện', '14');
INSERT INTO quanhuyen VALUES ('122', N'Huyện Phù Yên', N'Huyện', '14');
INSERT INTO quanhuyen VALUES ('123', N'Huyện Mộc Châu', N'Huyện', '14');
INSERT INTO quanhuyen VALUES ('124', N'Huyện Yên Châu', N'Huyện', '14');
INSERT INTO quanhuyen VALUES ('125', N'Huyện Mai Sơn', N'Huyện', '14');
INSERT INTO quanhuyen VALUES ('126', N'Huyện Sông Mã', N'Huyện', '14');
INSERT INTO quanhuyen VALUES ('127', N'Huyện Sốp Cộp', N'Huyện', '14');
INSERT INTO quanhuyen VALUES ('128', N'Huyện Vân Hồ', N'Huyện', '14');
INSERT INTO quanhuyen VALUES ('132', N'Thành phố Yên Bái', N'Thành phố', '15');
INSERT INTO quanhuyen VALUES ('133', N'Thị xã Nghĩa Lộ', N'Thị xã', '15');
INSERT INTO quanhuyen VALUES ('135', N'Huyện Lục Yên', N'Huyện', '15');
INSERT INTO quanhuyen VALUES ('136', N'Huyện Văn Yên', N'Huyện', '15');
INSERT INTO quanhuyen VALUES ('137', N'Huyện Mù Căng Chải', N'Huyện', '15');
INSERT INTO quanhuyen VALUES ('138', N'Huyện Trấn Yên', N'Huyện', '15');
INSERT INTO quanhuyen VALUES ('139', N'Huyện Trạm Tấu', N'Huyện', '15');
INSERT INTO quanhuyen VALUES ('140', N'Huyện Văn Chấn', N'Huyện', '15');
INSERT INTO quanhuyen VALUES ('141', N'Huyện Yên Bình', N'Huyện', '15');
INSERT INTO quanhuyen VALUES ('148', N'Thành phố Hòa Bình', N'Thành phố', '17');
INSERT INTO quanhuyen VALUES ('150', N'Huyện Đà Bắc', N'Huyện', '17');
INSERT INTO quanhuyen VALUES ('151', N'Huyện Kỳ Sơn', N'Huyện', '17');
INSERT INTO quanhuyen VALUES ('152', N'Huyện Lương Sơn', N'Huyện', '17');
INSERT INTO quanhuyen VALUES ('153', N'Huyện Kim Bôi', N'Huyện', '17');
INSERT INTO quanhuyen VALUES ('154', N'Huyện Cao Phong', N'Huyện', '17');
INSERT INTO quanhuyen VALUES ('155', N'Huyện Tân Lạc', N'Huyện', '17');
INSERT INTO quanhuyen VALUES ('156', N'Huyện Mai Châu', N'Huyện', '17');
INSERT INTO quanhuyen VALUES ('157', N'Huyện Lạc Sơn', N'Huyện', '17');
INSERT INTO quanhuyen VALUES ('158', N'Huyện Yên Thủy', N'Huyện', '17');
INSERT INTO quanhuyen VALUES ('159', N'Huyện Lạc Thủy', N'Huyện', '17');
INSERT INTO quanhuyen VALUES ('164', N'Thành phố Thái Nguyên', N'Thành phố', '19');
INSERT INTO quanhuyen VALUES ('165', N'Thành phố Sông Công', N'Thành phố', '19');
INSERT INTO quanhuyen VALUES ('167', N'Huyện Định Hóa', N'Huyện', '19');
INSERT INTO quanhuyen VALUES ('168', N'Huyện Phú Lương', N'Huyện', '19');
INSERT INTO quanhuyen VALUES ('169', N'Huyện Đồng Hỷ', N'Huyện', '19');
INSERT INTO quanhuyen VALUES ('170', N'Huyện Võ Nhai', N'Huyện', '19');
INSERT INTO quanhuyen VALUES ('171', N'Huyện Đại Từ', N'Huyện', '19');
INSERT INTO quanhuyen VALUES ('172', N'Thị xã Phổ Yên', N'Thị xã', '19');
INSERT INTO quanhuyen VALUES ('173', N'Huyện Phú Bình', N'Huyện', '19');
INSERT INTO quanhuyen VALUES ('178', N'Thành phố Lạng Sơn', N'Thành phố', '20');
INSERT INTO quanhuyen VALUES ('180', N'Huyện Tràng Định', N'Huyện', '20');
INSERT INTO quanhuyen VALUES ('181', N'Huyện Bình Gia', N'Huyện', '20');
INSERT INTO quanhuyen VALUES ('182', N'Huyện Văn Lãng', N'Huyện', '20');
INSERT INTO quanhuyen VALUES ('183', N'Huyện Cao Lộc', N'Huyện', '20');
INSERT INTO quanhuyen VALUES ('184', N'Huyện Văn Quan', N'Huyện', '20');
INSERT INTO quanhuyen VALUES ('185', N'Huyện Bắc Sơn', N'Huyện', '20');
INSERT INTO quanhuyen VALUES ('186', N'Huyện Hữu Lũng', N'Huyện', '20');
INSERT INTO quanhuyen VALUES ('187', N'Huyện Chi Lăng', N'Huyện', '20');
INSERT INTO quanhuyen VALUES ('188', N'Huyện Lộc Bình', N'Huyện', '20');
INSERT INTO quanhuyen VALUES ('189', N'Huyện Đình Lập', N'Huyện', '20');
INSERT INTO quanhuyen VALUES ('193', N'Thành phố Hạ Long', N'Thành phố', '22');
INSERT INTO quanhuyen VALUES ('194', N'Thành phố Móng Cái', N'Thành phố', '22');
INSERT INTO quanhuyen VALUES ('195', N'Thành phố Cẩm Phả', N'Thành phố', '22');
INSERT INTO quanhuyen VALUES ('196', N'Thành phố Uông Bí', N'Thành phố', '22');
INSERT INTO quanhuyen VALUES ('198', N'Huyện Bình Liêu', N'Huyện', '22');
INSERT INTO quanhuyen VALUES ('199', N'Huyện Tiên Yên', N'Huyện', '22');
INSERT INTO quanhuyen VALUES ('200', N'Huyện Đầm Hà', N'Huyện', '22');
INSERT INTO quanhuyen VALUES ('201', N'Huyện Hải Hà', N'Huyện', '22');
INSERT INTO quanhuyen VALUES ('202', N'Huyện Ba Chẽ', N'Huyện', '22');
INSERT INTO quanhuyen VALUES ('203', N'Huyện Vân Đồn', N'Huyện', '22');
INSERT INTO quanhuyen VALUES ('204', N'Huyện Hoành Bồ', N'Huyện', '22');
INSERT INTO quanhuyen VALUES ('205', N'Thị xã Đông Triều', N'Thị xã', '22');
INSERT INTO quanhuyen VALUES ('206', N'Thị xã Quảng Yên', N'Thị xã', '22');
INSERT INTO quanhuyen VALUES ('207', N'Huyện Cô Tô', N'Huyện', '22');
INSERT INTO quanhuyen VALUES ('213', N'Thành phố Bắc Giang', N'Thành phố', '24');
INSERT INTO quanhuyen VALUES ('215', N'Huyện Yên Thế', N'Huyện', '24');
INSERT INTO quanhuyen VALUES ('216', N'Huyện Tân Yên', N'Huyện', '24');
INSERT INTO quanhuyen VALUES ('217', N'Huyện Lạng Giang', N'Huyện', '24');
INSERT INTO quanhuyen VALUES ('218', N'Huyện Lục Nam', N'Huyện', '24');
INSERT INTO quanhuyen VALUES ('219', N'Huyện Lục Ngạn', N'Huyện', '24');
INSERT INTO quanhuyen VALUES ('220', N'Huyện Sơn Động', N'Huyện', '24');
INSERT INTO quanhuyen VALUES ('221', N'Huyện Yên Dũng', N'Huyện', '24');
INSERT INTO quanhuyen VALUES ('222', N'Huyện Việt Yên', N'Huyện', '24');
INSERT INTO quanhuyen VALUES ('223', N'Huyện Hiệp Hòa', N'Huyện', '24');
INSERT INTO quanhuyen VALUES ('227', N'Thành phố Việt Trì', N'Thành phố', '25');
INSERT INTO quanhuyen VALUES ('228', N'Thị xã Phú Thọ', N'Thị xã', '25');
INSERT INTO quanhuyen VALUES ('230', N'Huyện Đoan Hùng', N'Huyện', '25');
INSERT INTO quanhuyen VALUES ('231', N'Huyện Hạ Hoà', N'Huyện', '25');
INSERT INTO quanhuyen VALUES ('232', N'Huyện Thanh Ba', N'Huyện', '25');
INSERT INTO quanhuyen VALUES ('233', N'Huyện Phù Ninh', N'Huyện', '25');
INSERT INTO quanhuyen VALUES ('234', N'Huyện Yên Lập', N'Huyện', '25');
INSERT INTO quanhuyen VALUES ('235', N'Huyện Cẩm Khê', N'Huyện', '25');
INSERT INTO quanhuyen VALUES ('236', N'Huyện Tam Nông', N'Huyện', '25');
INSERT INTO quanhuyen VALUES ('237', N'Huyện Lâm Thao', N'Huyện', '25');
INSERT INTO quanhuyen VALUES ('238', N'Huyện Thanh Sơn', N'Huyện', '25');
INSERT INTO quanhuyen VALUES ('239', N'Huyện Thanh Thuỷ', N'Huyện', '25');
INSERT INTO quanhuyen VALUES ('240', N'Huyện Tân Sơn', N'Huyện', '25');
INSERT INTO quanhuyen VALUES ('243', N'Thành phố Vĩnh Yên', N'Thành phố', '26');
INSERT INTO quanhuyen VALUES ('244', N'Thị xã Phúc Yên', N'Thị xã', '26');
INSERT INTO quanhuyen VALUES ('246', N'Huyện Lập Thạch', N'Huyện', '26');
INSERT INTO quanhuyen VALUES ('247', N'Huyện Tam Dương', N'Huyện', '26');
INSERT INTO quanhuyen VALUES ('248', N'Huyện Tam Đảo', N'Huyện', '26');
INSERT INTO quanhuyen VALUES ('249', N'Huyện Bình Xuyên', N'Huyện', '26');
INSERT INTO quanhuyen VALUES ('250', N'Huyện Mê Linh', N'Huyện', '01');
INSERT INTO quanhuyen VALUES ('251', N'Huyện Yên Lạc', N'Huyện', '26');
INSERT INTO quanhuyen VALUES ('252', N'Huyện Vĩnh Tường', N'Huyện', '26');
INSERT INTO quanhuyen VALUES ('253', N'Huyện Sông Lô', N'Huyện', '26');
INSERT INTO quanhuyen VALUES ('256', N'Thành phố Bắc Ninh', N'Thành phố', '27');
INSERT INTO quanhuyen VALUES ('258', N'Huyện Yên Phong', N'Huyện', '27');
INSERT INTO quanhuyen VALUES ('259', N'Huyện Quế Võ', N'Huyện', '27');
INSERT INTO quanhuyen VALUES ('260', N'Huyện Tiên Du', N'Huyện', '27');
INSERT INTO quanhuyen VALUES ('261', N'Thị xã Từ Sơn', N'Thị xã', '27');
INSERT INTO quanhuyen VALUES ('262', N'Huyện Thuận Thành', N'Huyện', '27');
INSERT INTO quanhuyen VALUES ('263', N'Huyện Gia Bình', N'Huyện', '27');
INSERT INTO quanhuyen VALUES ('264', N'Huyện Lương Tài', N'Huyện', '27');
INSERT INTO quanhuyen VALUES ('268', N'Quận Hà Đông', N'Quận', '01');
INSERT INTO quanhuyen VALUES ('269', N'Thị xã Sơn Tây', N'Thị xã', '01');
INSERT INTO quanhuyen VALUES ('271', N'Huyện Ba Vì', N'Huyện', '01');
INSERT INTO quanhuyen VALUES ('272', N'Huyện Phúc Thọ', N'Huyện', '01');
INSERT INTO quanhuyen VALUES ('273', N'Huyện Đan Phượng', N'Huyện', '01');
INSERT INTO quanhuyen VALUES ('274', N'Huyện Hoài Đức', N'Huyện', '01');
INSERT INTO quanhuyen VALUES ('275', N'Huyện Quốc Oai', N'Huyện', '01');
INSERT INTO quanhuyen VALUES ('276', N'Huyện Thạch Thất', N'Huyện', '01');
INSERT INTO quanhuyen VALUES ('277', N'Huyện Chương Mỹ', N'Huyện', '01');
INSERT INTO quanhuyen VALUES ('278', N'Huyện Thanh Oai', N'Huyện', '01');
INSERT INTO quanhuyen VALUES ('279', N'Huyện Thường Tín', N'Huyện', '01');
INSERT INTO quanhuyen VALUES ('280', N'Huyện Phú Xuyên', N'Huyện', '01');
INSERT INTO quanhuyen VALUES ('281', N'Huyện Ứng Hòa', N'Huyện', '01');
INSERT INTO quanhuyen VALUES ('282', N'Huyện Mỹ Đức', N'Huyện', '01');
INSERT INTO quanhuyen VALUES ('288', N'Thành phố Hải Dương', N'Thành phố', '30');
INSERT INTO quanhuyen VALUES ('290', N'Thị xã Chí Linh', N'Thị xã', '30');
INSERT INTO quanhuyen VALUES ('291', N'Huyện Nam Sách', N'Huyện', '30');
INSERT INTO quanhuyen VALUES ('292', N'Huyện Kinh Môn', N'Huyện', '30');
INSERT INTO quanhuyen VALUES ('293', N'Huyện Kim Thành', N'Huyện', '30');
INSERT INTO quanhuyen VALUES ('294', N'Huyện Thanh Hà', N'Huyện', '30');
INSERT INTO quanhuyen VALUES ('295', N'Huyện Cẩm Giàng', N'Huyện', '30');
INSERT INTO quanhuyen VALUES ('296', N'Huyện Bình Giang', N'Huyện', '30');
INSERT INTO quanhuyen VALUES ('297', N'Huyện Gia Lộc', N'Huyện', '30');
INSERT INTO quanhuyen VALUES ('298', N'Huyện Tứ Kỳ', N'Huyện', '30');
INSERT INTO quanhuyen VALUES ('299', N'Huyện Ninh Giang', N'Huyện', '30');
INSERT INTO quanhuyen VALUES ('300', N'Huyện Thanh Miện', N'Huyện', '30');
INSERT INTO quanhuyen VALUES ('303', N'Quận Hồng Bàng', N'Quận', '31');
INSERT INTO quanhuyen VALUES ('304', N'Quận Ngô Quyền', N'Quận', '31');
INSERT INTO quanhuyen VALUES ('305', N'Quận Lê Chân', N'Quận', '31');
INSERT INTO quanhuyen VALUES ('306', N'Quận Hải An', N'Quận', '31');
INSERT INTO quanhuyen VALUES ('307', N'Quận Kiến An', N'Quận', '31');
INSERT INTO quanhuyen VALUES ('308', N'Quận Đồ Sơn', N'Quận', '31');
INSERT INTO quanhuyen VALUES ('309', N'Quận Dương Kinh', N'Quận', '31');
INSERT INTO quanhuyen VALUES ('311', N'Huyện Thuỷ Nguyên', N'Huyện', '31');
INSERT INTO quanhuyen VALUES ('312', N'Huyện An Dương', N'Huyện', '31');
INSERT INTO quanhuyen VALUES ('313', N'Huyện An Lão', N'Huyện', '31');
INSERT INTO quanhuyen VALUES ('314', N'Huyện Kiến Thuỵ', N'Huyện', '31');
INSERT INTO quanhuyen VALUES ('315', N'Huyện Tiên Lãng', N'Huyện', '31');
INSERT INTO quanhuyen VALUES ('316', N'Huyện Vĩnh Bảo', N'Huyện', '31');
INSERT INTO quanhuyen VALUES ('317', N'Huyện Cát Hải', N'Huyện', '31');
INSERT INTO quanhuyen VALUES ('318', N'Huyện Bạch Long Vĩ', N'Huyện', '31');
INSERT INTO quanhuyen VALUES ('323', N'Thành phố Hưng Yên', N'Thành phố', '33');
INSERT INTO quanhuyen VALUES ('325', N'Huyện Văn Lâm', N'Huyện', '33');
INSERT INTO quanhuyen VALUES ('326', N'Huyện Văn Giang', N'Huyện', '33');
INSERT INTO quanhuyen VALUES ('327', N'Huyện Yên Mỹ', N'Huyện', '33');
INSERT INTO quanhuyen VALUES ('328', N'Huyện Mỹ Hào', N'Huyện', '33');
INSERT INTO quanhuyen VALUES ('329', N'Huyện Ân Thi', N'Huyện', '33');
INSERT INTO quanhuyen VALUES ('330', N'Huyện Khoái Châu', N'Huyện', '33');
INSERT INTO quanhuyen VALUES ('331', N'Huyện Kim Động', N'Huyện', '33');
INSERT INTO quanhuyen VALUES ('332', N'Huyện Tiên Lữ', N'Huyện', '33');
INSERT INTO quanhuyen VALUES ('333', N'Huyện Phù Cừ', N'Huyện', '33');
INSERT INTO quanhuyen VALUES ('336', N'Thành phố Thái Bình', N'Thành phố', '34');
INSERT INTO quanhuyen VALUES ('338', N'Huyện Quỳnh Phụ', N'Huyện', '34');
INSERT INTO quanhuyen VALUES ('339', N'Huyện Hưng Hà', N'Huyện', '34');
INSERT INTO quanhuyen VALUES ('340', N'Huyện Đông Hưng', N'Huyện', '34');
INSERT INTO quanhuyen VALUES ('341', N'Huyện Thái Thụy', N'Huyện', '34');
INSERT INTO quanhuyen VALUES ('342', N'Huyện Tiền Hải', N'Huyện', '34');
INSERT INTO quanhuyen VALUES ('343', N'Huyện Kiến Xương', N'Huyện', '34');
INSERT INTO quanhuyen VALUES ('344', N'Huyện Vũ Thư', N'Huyện', '34');
INSERT INTO quanhuyen VALUES ('347', N'Thành phố Phủ Lý', N'Thành phố', '35');
INSERT INTO quanhuyen VALUES ('349', N'Huyện Duy Tiên', N'Huyện', '35');
INSERT INTO quanhuyen VALUES ('350', N'Huyện Kim Bảng', N'Huyện', '35');
INSERT INTO quanhuyen VALUES ('351', N'Huyện Thanh Liêm', N'Huyện', '35');
INSERT INTO quanhuyen VALUES ('352', N'Huyện Bình Lục', N'Huyện', '35');
INSERT INTO quanhuyen VALUES ('353', N'Huyện Lý Nhân', N'Huyện', '35');
INSERT INTO quanhuyen VALUES ('356', N'Thành phố Nam Định', N'Thành phố', '36');
INSERT INTO quanhuyen VALUES ('358', N'Huyện Mỹ Lộc', N'Huyện', '36');
INSERT INTO quanhuyen VALUES ('359', N'Huyện Vụ Bản', N'Huyện', '36');
INSERT INTO quanhuyen VALUES ('360', N'Huyện Ý Yên', N'Huyện', '36');
INSERT INTO quanhuyen VALUES ('361', N'Huyện Nghĩa Hưng', N'Huyện', '36');
INSERT INTO quanhuyen VALUES ('362', N'Huyện Nam Trực', N'Huyện', '36');
INSERT INTO quanhuyen VALUES ('363', N'Huyện Trực Ninh', N'Huyện', '36');
INSERT INTO quanhuyen VALUES ('364', N'Huyện Xuân Trường', N'Huyện', '36');
INSERT INTO quanhuyen VALUES ('365', N'Huyện Giao Thủy', N'Huyện', '36');
INSERT INTO quanhuyen VALUES ('366', N'Huyện Hải Hậu', N'Huyện', '36');
INSERT INTO quanhuyen VALUES ('369', N'Thành phố Ninh Bình', N'Thành phố', '37');
INSERT INTO quanhuyen VALUES ('370', N'Thành phố Tam Điệp', N'Thành phố', '37');
INSERT INTO quanhuyen VALUES ('372', N'Huyện Nho Quan', N'Huyện', '37');
INSERT INTO quanhuyen VALUES ('373', N'Huyện Gia Viễn', N'Huyện', '37');
INSERT INTO quanhuyen VALUES ('374', N'Huyện Hoa Lư', N'Huyện', '37');
INSERT INTO quanhuyen VALUES ('375', N'Huyện Yên Khánh', N'Huyện', '37');
INSERT INTO quanhuyen VALUES ('376', N'Huyện Kim Sơn', N'Huyện', '37');
INSERT INTO quanhuyen VALUES ('377', N'Huyện Yên Mô', N'Huyện', '37');
INSERT INTO quanhuyen VALUES ('380', N'Thành phố Thanh Hóa', N'Thành phố', '38');
INSERT INTO quanhuyen VALUES ('381', N'Thị xã Bỉm Sơn', N'Thị xã', '38');
INSERT INTO quanhuyen VALUES ('382', N'Thị xã Sầm Sơn', N'Thị xã', '38');
INSERT INTO quanhuyen VALUES ('384', N'Huyện Mường Lát', N'Huyện', '38');
INSERT INTO quanhuyen VALUES ('385', N'Huyện Quan Hóa', N'Huyện', '38');
INSERT INTO quanhuyen VALUES ('386', N'Huyện Bá Thước', N'Huyện', '38');
INSERT INTO quanhuyen VALUES ('387', N'Huyện Quan Sơn', N'Huyện', '38');
INSERT INTO quanhuyen VALUES ('388', N'Huyện Lang Chánh', N'Huyện', '38');
INSERT INTO quanhuyen VALUES ('389', N'Huyện Ngọc Lặc', N'Huyện', '38');
INSERT INTO quanhuyen VALUES ('390', N'Huyện Cẩm Thủy', N'Huyện', '38');
INSERT INTO quanhuyen VALUES ('391', N'Huyện Thạch Thành', N'Huyện', '38');
INSERT INTO quanhuyen VALUES ('392', N'Huyện Hà Trung', N'Huyện', '38');
INSERT INTO quanhuyen VALUES ('393', N'Huyện Vĩnh Lộc', N'Huyện', '38');
INSERT INTO quanhuyen VALUES ('394', N'Huyện Yên Định', N'Huyện', '38');
INSERT INTO quanhuyen VALUES ('395', N'Huyện Thọ Xuân', N'Huyện', '38');
INSERT INTO quanhuyen VALUES ('396', N'Huyện Thường Xuân', N'Huyện', '38');
INSERT INTO quanhuyen VALUES ('397', N'Huyện Triệu Sơn', N'Huyện', '38');
INSERT INTO quanhuyen VALUES ('398', N'Huyện Thiệu Hóa', N'Huyện', '38');
INSERT INTO quanhuyen VALUES ('399', N'Huyện Hoằng Hóa', N'Huyện', '38');
INSERT INTO quanhuyen VALUES ('400', N'Huyện Hậu Lộc', N'Huyện', '38');
INSERT INTO quanhuyen VALUES ('401', N'Huyện Nga Sơn', N'Huyện', '38');
INSERT INTO quanhuyen VALUES ('402', N'Huyện Như Xuân', N'Huyện', '38');
INSERT INTO quanhuyen VALUES ('403', N'Huyện Như Thanh', N'Huyện', '38');
INSERT INTO quanhuyen VALUES ('404', N'Huyện Nông Cống', N'Huyện', '38');
INSERT INTO quanhuyen VALUES ('405', N'Huyện Đông Sơn', N'Huyện', '38');
INSERT INTO quanhuyen VALUES ('406', N'Huyện Quảng Xương', N'Huyện', '38');
INSERT INTO quanhuyen VALUES ('407', N'Huyện Tĩnh Gia', N'Huyện', '38');
INSERT INTO quanhuyen VALUES ('412', N'Thành phố Vinh', N'Thành phố', '40');
INSERT INTO quanhuyen VALUES ('413', N'Thị xã Cửa Lò', N'Thị xã', '40');
INSERT INTO quanhuyen VALUES ('414', N'Thị xã Thái Hoà', N'Thị xã', '40');
INSERT INTO quanhuyen VALUES ('415', N'Huyện Quế Phong', N'Huyện', '40');
INSERT INTO quanhuyen VALUES ('416', N'Huyện Quỳ Châu', N'Huyện', '40');
INSERT INTO quanhuyen VALUES ('417', N'Huyện Kỳ Sơn', N'Huyện', '40');
INSERT INTO quanhuyen VALUES ('418', N'Huyện Tương Dương', N'Huyện', '40');
INSERT INTO quanhuyen VALUES ('419', N'Huyện Nghĩa Đàn', N'Huyện', '40');
INSERT INTO quanhuyen VALUES ('420', N'Huyện Quỳ Hợp', N'Huyện', '40');
INSERT INTO quanhuyen VALUES ('421', N'Huyện Quỳnh Lưu', N'Huyện', '40');
INSERT INTO quanhuyen VALUES ('422', N'Huyện Con Cuông', N'Huyện', '40');
INSERT INTO quanhuyen VALUES ('423', N'Huyện Tân Kỳ', N'Huyện', '40');
INSERT INTO quanhuyen VALUES ('424', N'Huyện Anh Sơn', N'Huyện', '40');
INSERT INTO quanhuyen VALUES ('425', N'Huyện Diễn Châu', N'Huyện', '40');
INSERT INTO quanhuyen VALUES ('426', N'Huyện Yên Thành', N'Huyện', '40');
INSERT INTO quanhuyen VALUES ('427', N'Huyện Đô Lương', N'Huyện', '40');
INSERT INTO quanhuyen VALUES ('428', N'Huyện Thanh Chương', N'Huyện', '40');
INSERT INTO quanhuyen VALUES ('429', N'Huyện Nghi Lộc', N'Huyện', '40');
INSERT INTO quanhuyen VALUES ('430', N'Huyện Nam Đàn', N'Huyện', '40');
INSERT INTO quanhuyen VALUES ('431', N'Huyện Hưng Nguyên', N'Huyện', '40');
INSERT INTO quanhuyen VALUES ('432', N'Thị xã Hoàng Mai', N'Thị xã', '40');
INSERT INTO quanhuyen VALUES ('436', N'Thành phố Hà Tĩnh', N'Thành phố', '42');
INSERT INTO quanhuyen VALUES ('437', N'Thị xã Hồng Lĩnh', N'Thị xã', '42');
INSERT INTO quanhuyen VALUES ('439', N'Huyện Hương Sơn', N'Huyện', '42');
INSERT INTO quanhuyen VALUES ('440', N'Huyện Đức Thọ', N'Huyện', '42');
INSERT INTO quanhuyen VALUES ('441', N'Huyện Vũ Quang', N'Huyện', '42');
INSERT INTO quanhuyen VALUES ('442', N'Huyện Nghi Xuân', N'Huyện', '42');
INSERT INTO quanhuyen VALUES ('443', N'Huyện Can Lộc', N'Huyện', '42');
INSERT INTO quanhuyen VALUES ('444', N'Huyện Hương Khê', N'Huyện', '42');
INSERT INTO quanhuyen VALUES ('445', N'Huyện Thạch Hà', N'Huyện', '42');
INSERT INTO quanhuyen VALUES ('446', N'Huyện Cẩm Xuyên', N'Huyện', '42');
INSERT INTO quanhuyen VALUES ('447', N'Huyện Kỳ Anh', N'Huyện', '42');
INSERT INTO quanhuyen VALUES ('448', N'Huyện Lộc Hà', N'Huyện', '42');
INSERT INTO quanhuyen VALUES ('449', N'Thị xã Kỳ Anh', N'Thị xã', '42');
INSERT INTO quanhuyen VALUES ('450', N'Thành Phố Đồng Hới', N'Thành phố', '44');
INSERT INTO quanhuyen VALUES ('452', N'Huyện Minh Hóa', N'Huyện', '44');
INSERT INTO quanhuyen VALUES ('453', N'Huyện Tuyên Hóa', N'Huyện', '44');
INSERT INTO quanhuyen VALUES ('454', N'Huyện Quảng Trạch', 'Thị xã', '44');
INSERT INTO quanhuyen VALUES ('455', N'Huyện Bố Trạch', N'Huyện', '44');
INSERT INTO quanhuyen VALUES ('456', N'Huyện Quảng Ninh', N'Huyện', '44');
INSERT INTO quanhuyen VALUES ('457', N'Huyện Lệ Thủy', N'Huyện', '44');
INSERT INTO quanhuyen VALUES ('458', N'Thị xã Ba Đồn', N'Huyện', '44');
INSERT INTO quanhuyen VALUES ('461', N'Thành phố Đông Hà', N'Thành phố', '45');
INSERT INTO quanhuyen VALUES ('462', N'Thị xã Quảng Trị', N'Thị xã', '45');
INSERT INTO quanhuyen VALUES ('464', N'Huyện Vĩnh Linh', N'Huyện', '45');
INSERT INTO quanhuyen VALUES ('465', N'Huyện Hướng Hóa', N'Huyện', '45');
INSERT INTO quanhuyen VALUES ('466', N'Huyện Gio Linh', N'Huyện', '45');
INSERT INTO quanhuyen VALUES ('467', N'Huyện Đa Krông', N'Huyện', '45');
INSERT INTO quanhuyen VALUES ('468', N'Huyện Cam Lộ', N'Huyện', '45');
INSERT INTO quanhuyen VALUES ('469', N'Huyện Triệu Phong', N'Huyện', '45');
INSERT INTO quanhuyen VALUES ('470', N'Huyện Hải Lăng', N'Huyện', '45');
INSERT INTO quanhuyen VALUES ('471', N'Huyện Cồn Cỏ', N'Huyện', '45');
INSERT INTO quanhuyen VALUES ('474', N'Thành phố Huế', N'Thành phố', '46');
INSERT INTO quanhuyen VALUES ('476', N'Huyện Phong Điền', N'Huyện', '46');
INSERT INTO quanhuyen VALUES ('477', N'Huyện Quảng Điền', N'Huyện', '46');
INSERT INTO quanhuyen VALUES ('478', N'Huyện Phú Vang', N'Huyện', '46');
INSERT INTO quanhuyen VALUES ('479', N'Thị xã Hương Thủy', N'Thị xã', '46');
INSERT INTO quanhuyen VALUES ('480', N'Thị xã Hương Trà', N'Thị xã', '46');
INSERT INTO quanhuyen VALUES ('481', N'Huyện A Lưới', N'Huyện', '46');
INSERT INTO quanhuyen VALUES ('482', N'Huyện Phú Lộc', N'Huyện', '46');
INSERT INTO quanhuyen VALUES ('483', N'Huyện Nam Đông', N'Huyện', '46');
INSERT INTO quanhuyen VALUES ('490', N'Quận Liên Chiểu', N'Quận', '48');
INSERT INTO quanhuyen VALUES ('491', N'Quận Thanh Khê', N'Quận', '48');
INSERT INTO quanhuyen VALUES ('492', N'Quận Hải Châu', N'Quận', '48');
INSERT INTO quanhuyen VALUES ('493', N'Quận Sơn Trà', N'Quận', '48');
INSERT INTO quanhuyen VALUES ('494', N'Quận Ngũ Hành Sơn', N'Quận', '48');
INSERT INTO quanhuyen VALUES ('495', N'Quận Cẩm Lệ', N'Quận', '48');
INSERT INTO quanhuyen VALUES ('497', N'Huyện Hòa Vang', N'Huyện', '48');
INSERT INTO quanhuyen VALUES ('498', N'Huyện Hoàng Sa', N'Huyện', '48');
INSERT INTO quanhuyen VALUES ('502', N'Thành phố Tam Kỳ', N'Thành phố', '49');
INSERT INTO quanhuyen VALUES ('503', N'Thành phố Hội An', N'Thành phố', '49');
INSERT INTO quanhuyen VALUES ('504', N'Huyện Tây Giang', N'Huyện', '49');
INSERT INTO quanhuyen VALUES ('505', N'Huyện Đông Giang', N'Huyện', '49');
INSERT INTO quanhuyen VALUES ('506', N'Huyện Đại Lộc', N'Huyện', '49');
INSERT INTO quanhuyen VALUES ('507', N'Thị xã Điện Bàn', N'Thị xã', '49');
INSERT INTO quanhuyen VALUES ('508', N'Huyện Duy Xuyên', N'Huyện', '49');
INSERT INTO quanhuyen VALUES ('509', N'Huyện Quế Sơn', N'Huyện', '49');
INSERT INTO quanhuyen VALUES ('510', N'Huyện Nam Giang', N'Huyện', '49');
INSERT INTO quanhuyen VALUES ('511', N'Huyện Phước Sơn', N'Huyện', '49');
INSERT INTO quanhuyen VALUES ('512', N'Huyện Hiệp Đức', N'Huyện', '49');
INSERT INTO quanhuyen VALUES ('513', N'Huyện Thăng Bình', N'Huyện', '49');
INSERT INTO quanhuyen VALUES ('514', N'Huyện Tiên Phước', N'Huyện', '49');
INSERT INTO quanhuyen VALUES ('515', N'Huyện Bắc Trà My', N'Huyện', '49');
INSERT INTO quanhuyen VALUES ('516', N'Huyện Nam Trà My', N'Huyện', '49');
INSERT INTO quanhuyen VALUES ('517', N'Huyện Núi Thành', N'Huyện', '49');
INSERT INTO quanhuyen VALUES ('518', N'Huyện Phú Ninh', N'Huyện', '49');
INSERT INTO quanhuyen VALUES ('519', N'Huyện Nông Sơn', N'Huyện', '49');
INSERT INTO quanhuyen VALUES ('522', N'Thành phố Quảng Ngãi', N'Thành phố', '51');
INSERT INTO quanhuyen VALUES ('524', N'Huyện Bình Sơn', N'Huyện', '51');
INSERT INTO quanhuyen VALUES ('525', N'Huyện Trà Bồng', N'Huyện', '51');
INSERT INTO quanhuyen VALUES ('526', N'Huyện Tây Trà', N'Huyện', '51');
INSERT INTO quanhuyen VALUES ('527', N'Huyện Sơn Tịnh', N'Huyện', '51');
INSERT INTO quanhuyen VALUES ('528', N'Huyện Tư Nghĩa', N'Huyện', '51');
INSERT INTO quanhuyen VALUES ('529', N'Huyện Sơn Hà', N'Huyện', '51');
INSERT INTO quanhuyen VALUES ('530', N'Huyện Sơn Tây', N'Huyện', '51');
INSERT INTO quanhuyen VALUES ('531', N'Huyện Minh Long', N'Huyện', '51');
INSERT INTO quanhuyen VALUES ('532', N'Huyện Nghĩa Hành', N'Huyện', '51');
INSERT INTO quanhuyen VALUES ('533', N'Huyện Mộ Đức', N'Huyện', '51');
INSERT INTO quanhuyen VALUES ('534', N'Huyện Đức Phổ', N'Huyện', '51');
INSERT INTO quanhuyen VALUES ('535', N'Huyện Ba Tơ', N'Huyện', '51');
INSERT INTO quanhuyen VALUES ('536', N'Huyện Lý Sơn', N'Huyện', '51');
INSERT INTO quanhuyen VALUES ('540', N'Thành phố Qui Nhơn', N'Thành phố', '52');
INSERT INTO quanhuyen VALUES ('542', N'Huyện An Lão', N'Huyện', '52');
INSERT INTO quanhuyen VALUES ('543', N'Huyện Hoài Nhơn', N'Huyện', '52');
INSERT INTO quanhuyen VALUES ('544', N'Huyện Hoài Ân', N'Huyện', '52');
INSERT INTO quanhuyen VALUES ('545', N'Huyện Phù Mỹ', N'Huyện', '52');
INSERT INTO quanhuyen VALUES ('546', N'Huyện Vĩnh Thạnh', N'Huyện', '52');
INSERT INTO quanhuyen VALUES ('547', N'Huyện Tây Sơn', N'Huyện', '52');
INSERT INTO quanhuyen VALUES ('548', N'Huyện Phù Cát', N'Huyện', '52');
INSERT INTO quanhuyen VALUES ('549', N'Thị xã An Nhơn', N'Thị xã', '52');
INSERT INTO quanhuyen VALUES ('550', N'Huyện Tuy Phước', N'Huyện', '52');
INSERT INTO quanhuyen VALUES ('551', N'Huyện Vân Canh', N'Huyện', '52');
INSERT INTO quanhuyen VALUES ('555', N'Thành phố Tuy Hoà', N'Thành phố', '54');
INSERT INTO quanhuyen VALUES ('557', N'Thị xã Sông Cầu', N'Thị xã', '54');
INSERT INTO quanhuyen VALUES ('558', N'Huyện Đồng Xuân', N'Huyện', '54');
INSERT INTO quanhuyen VALUES ('559', N'Huyện Tuy An', N'Huyện', '54');
INSERT INTO quanhuyen VALUES ('560', N'Huyện Sơn Hòa', N'Huyện', '54');
INSERT INTO quanhuyen VALUES ('561', N'Huyện Sông Hinh', N'Huyện', '54');
INSERT INTO quanhuyen VALUES ('562', N'Huyện Tây Hoà', N'Huyện', '54');
INSERT INTO quanhuyen VALUES ('563', N'Huyện Phú Hoà', N'Huyện', '54');
INSERT INTO quanhuyen VALUES ('564', N'Huyện Đông Hòa', N'Huyện', '54');
INSERT INTO quanhuyen VALUES ('568', N'Thành phố Nha Trang', N'Thành phố', '56');
INSERT INTO quanhuyen VALUES ('569', N'Thành phố Cam Ranh', N'Thành phố', '56');
INSERT INTO quanhuyen VALUES ('570', N'Huyện Cam Lâm', N'Huyện', '56');
INSERT INTO quanhuyen VALUES ('571', N'Huyện Vạn Ninh', N'Huyện', '56');
INSERT INTO quanhuyen VALUES ('572', N'Thị xã Ninh Hòa', N'Thị xã', '56');
INSERT INTO quanhuyen VALUES ('573', N'Huyện Khánh Vĩnh', N'Huyện', '56');
INSERT INTO quanhuyen VALUES ('574', N'Huyện Diên Khánh', N'Huyện', '56');
INSERT INTO quanhuyen VALUES ('575', N'Huyện Khánh Sơn', N'Huyện', '56');
INSERT INTO quanhuyen VALUES ('576', N'Huyện Trường Sa', N'Huyện', '56');
INSERT INTO quanhuyen VALUES ('582', N'Thành phố Phan Rang-Tháp Chàm', N'Thành phố', '58');
INSERT INTO quanhuyen VALUES ('584', N'Huyện Bác Ái', N'Huyện', '58');
INSERT INTO quanhuyen VALUES ('585', N'Huyện Ninh Sơn', N'Huyện', '58');
INSERT INTO quanhuyen VALUES ('586', N'Huyện Ninh Hải', N'Huyện', '58');
INSERT INTO quanhuyen VALUES ('587', N'Huyện Ninh Phước', N'Huyện', '58');
INSERT INTO quanhuyen VALUES ('588', N'Huyện Thuận Bắc', N'Huyện', '58');
INSERT INTO quanhuyen VALUES ('589', N'Huyện Thuận Nam', N'Huyện', '58');
INSERT INTO quanhuyen VALUES ('593', N'Thành phố Phan Thiết', N'Thành phố', '60');
INSERT INTO quanhuyen VALUES ('594', N'Thị xã La Gi', N'Thị xã', '60');
INSERT INTO quanhuyen VALUES ('595', N'Huyện Tuy Phong', N'Huyện', '60');
INSERT INTO quanhuyen VALUES ('596', N'Huyện Bắc Bình', N'Huyện', '60');
INSERT INTO quanhuyen VALUES ('597', N'Huyện Hàm Thuận Bắc', N'Huyện', '60');
INSERT INTO quanhuyen VALUES ('598', N'Huyện Hàm Thuận Nam', N'Huyện', '60');
INSERT INTO quanhuyen VALUES ('599', N'Huyện Tánh Linh', N'Huyện', '60');
INSERT INTO quanhuyen VALUES ('600', N'Huyện Đức Linh', N'Huyện', '60');
INSERT INTO quanhuyen VALUES ('601', N'Huyện Hàm Tân', N'Huyện', '60');
INSERT INTO quanhuyen VALUES ('602', N'Huyện Phú Quí', N'Huyện', '60');
INSERT INTO quanhuyen VALUES ('608', N'Thành phố Kon Tum', N'Thành phố', '62');
INSERT INTO quanhuyen VALUES ('610', N'Huyện Đắk Glei', N'Huyện', '62');
INSERT INTO quanhuyen VALUES ('611', N'Huyện Ngọc Hồi', N'Huyện', '62');
INSERT INTO quanhuyen VALUES ('612', N'Huyện Đắk Tô', N'Huyện', '62');
INSERT INTO quanhuyen VALUES ('613', N'Huyện Kon Plông', N'Huyện', '62');
INSERT INTO quanhuyen VALUES ('614', N'Huyện Kon Rẫy', N'Huyện', '62');
INSERT INTO quanhuyen VALUES ('615', N'Huyện Đắk Hà', N'Huyện', '62');
INSERT INTO quanhuyen VALUES ('616', N'Huyện Sa Thầy', N'Huyện', '62');
INSERT INTO quanhuyen VALUES ('617', N'Huyện Tu Mơ Rông', N'Huyện', '62');
INSERT INTO quanhuyen VALUES ('618', N'Huyện Ia H Drai', N'Huyện', '62');
INSERT INTO quanhuyen VALUES ('622', N'Thành phố Pleiku', N'Thành phố', '64');
INSERT INTO quanhuyen VALUES ('623', N'Thị xã An Khê', N'Thị xã', '64');
INSERT INTO quanhuyen VALUES ('624', N'Thị xã Ayun Pa', N'Thị xã', '64');
INSERT INTO quanhuyen VALUES ('625', N'Huyện KBang', N'Huyện', '64');
INSERT INTO quanhuyen VALUES ('626', N'Huyện Đăk Đoa', N'Huyện', '64');
INSERT INTO quanhuyen VALUES ('627', N'Huyện Chư Păh', N'Huyện', '64');
INSERT INTO quanhuyen VALUES ('628', N'Huyện Ia Grai', N'Huyện', '64');
INSERT INTO quanhuyen VALUES ('629', N'Huyện Mang Yang', N'Huyện', '64');
INSERT INTO quanhuyen VALUES ('630', N'Huyện Kông Chro', N'Huyện', '64');
INSERT INTO quanhuyen VALUES ('631', N'Huyện Đức Cơ', N'Huyện', '64');
INSERT INTO quanhuyen VALUES ('632', N'Huyện Chư Prông', N'Huyện', '64');
INSERT INTO quanhuyen VALUES ('633', N'Huyện Chư Sê', N'Huyện', '64');
INSERT INTO quanhuyen VALUES ('634', N'Huyện Đăk Pơ', N'Huyện', '64');
INSERT INTO quanhuyen VALUES ('635', N'Huyện Ia Pa', N'Huyện', '64');
INSERT INTO quanhuyen VALUES ('637', N'Huyện Krông Pa', N'Huyện', '64');
INSERT INTO quanhuyen VALUES ('638', N'Huyện Phú Thiện', N'Huyện', '64');
INSERT INTO quanhuyen VALUES ('639', N'Huyện Chư Pưh', N'Huyện', '64');
INSERT INTO quanhuyen VALUES ('643', N'Thành phố Buôn Ma Thuột', N'Thành phố', '66');
INSERT INTO quanhuyen VALUES ('644', N'Thị Xã Buôn Hồ', N'Thị xã', '66');
INSERT INTO quanhuyen VALUES ('645', N'Huyện Ea Hleo', N'Huyện', '66');
INSERT INTO quanhuyen VALUES ('646', N'Huyện Ea Súp', N'Huyện', '66');
INSERT INTO quanhuyen VALUES ('647', N'Huyện Buôn Đôn', N'Huyện', '66');
INSERT INTO quanhuyen VALUES ('648', N'Huyện Cư Mgar', N'Huyện', '66');
INSERT INTO quanhuyen VALUES ('649', N'Huyện Krông Búk', N'Huyện', '66');
INSERT INTO quanhuyen VALUES ('650', N'Huyện Krông Năng', N'Huyện', '66');
INSERT INTO quanhuyen VALUES ('651', N'Huyện Ea Kar', N'Huyện', '66');
INSERT INTO quanhuyen VALUES ('652', N'Huyện MĐrắk', N'Huyện', '66');
INSERT INTO quanhuyen VALUES ('653', N'Huyện Krông Bông', N'Huyện', '66');
INSERT INTO quanhuyen VALUES ('654', N'Huyện Krông Pắc', N'Huyện', '66');
INSERT INTO quanhuyen VALUES ('655', N'Huyện Krông A Na', N'Huyện', '66');
INSERT INTO quanhuyen VALUES ('656', N'Huyện Lắk', N'Huyện', '66');
INSERT INTO quanhuyen VALUES ('657', N'Huyện Cư Kuin', N'Huyện', '66');
INSERT INTO quanhuyen VALUES ('660', N'Thị xã Gia Nghĩa', N'Thị xã', '67');
INSERT INTO quanhuyen VALUES ('661', N'Huyện Đăk Glong', N'Huyện', '67');
INSERT INTO quanhuyen VALUES ('662', N'Huyện Cư Jút', N'Huyện', '67');
INSERT INTO quanhuyen VALUES ('663', N'Huyện Đắk Mil', N'Huyện', '67');
INSERT INTO quanhuyen VALUES ('664', N'Huyện Krông Nô', N'Huyện', '67');
INSERT INTO quanhuyen VALUES ('665', N'Huyện Đắk Song', N'Huyện', '67');
INSERT INTO quanhuyen VALUES ('666', N'Huyện Đắk RLấp', N'Huyện', '67');
INSERT INTO quanhuyen VALUES ('667', N'Huyện Tuy Đức', N'Huyện', '67');
INSERT INTO quanhuyen VALUES ('672', N'Thành phố Đà Lạt', N'Thành phố', '68');
INSERT INTO quanhuyen VALUES ('673', N'Thành phố Bảo Lộc', N'Thành phố', '68');
INSERT INTO quanhuyen VALUES ('674', N'Huyện Đam Rông', N'Huyện', '68');
INSERT INTO quanhuyen VALUES ('675', N'Huyện Lạc Dương', N'Huyện', '68');
INSERT INTO quanhuyen VALUES ('676', N'Huyện Lâm Hà', N'Huyện', '68');
INSERT INTO quanhuyen VALUES ('677', N'Huyện Đơn Dương', N'Huyện', '68');
INSERT INTO quanhuyen VALUES ('678', N'Huyện Đức Trọng', N'Huyện', '68');
INSERT INTO quanhuyen VALUES ('679', N'Huyện Di Linh', N'Huyện', '68');
INSERT INTO quanhuyen VALUES ('680', N'Huyện Bảo Lâm', N'Huyện', '68');
INSERT INTO quanhuyen VALUES ('681', N'Huyện Đạ Huoai', N'Huyện', '68');
INSERT INTO quanhuyen VALUES ('682', N'Huyện Đạ Tẻh', N'Huyện', '68');
INSERT INTO quanhuyen VALUES ('683', N'Huyện Cát Tiên', N'Huyện', '68');
INSERT INTO quanhuyen VALUES ('688', N'Thị xã Phước Long', N'Thị xã', '70');
INSERT INTO quanhuyen VALUES ('689', N'Thị xã Đồng Xoài', N'Thị xã', '70');
INSERT INTO quanhuyen VALUES ('690', N'Thị xã Bình Long', N'Thị xã', '70');
INSERT INTO quanhuyen VALUES ('691', N'Huyện Bù Gia Mập', N'Huyện', '70');
INSERT INTO quanhuyen VALUES ('692', N'Huyện Lộc Ninh', N'Huyện', '70');
INSERT INTO quanhuyen VALUES ('693', N'Huyện Bù Đốp', N'Huyện', '70');
INSERT INTO quanhuyen VALUES ('694', N'Huyện Hớn Quản', N'Huyện', '70');
INSERT INTO quanhuyen VALUES ('695', N'Huyện Đồng Phú', N'Huyện', '70');
INSERT INTO quanhuyen VALUES ('696', N'Huyện Bù Đăng', N'Huyện', '70');
INSERT INTO quanhuyen VALUES ('697', N'Huyện Chơn Thành', N'Huyện', '70');
INSERT INTO quanhuyen VALUES ('698', N'Huyện Phú Riềng', N'Huyện', '70');
INSERT INTO quanhuyen VALUES ('703', N'Thành phố Tây Ninh', N'Thành phố', '72');
INSERT INTO quanhuyen VALUES ('705', N'Huyện Tân Biên', N'Huyện', '72');
INSERT INTO quanhuyen VALUES ('706', N'Huyện Tân Châu', N'Huyện', '72');
INSERT INTO quanhuyen VALUES ('707', N'Huyện Dương Minh Châu', N'Huyện', '72');
INSERT INTO quanhuyen VALUES ('708', N'Huyện Châu Thành', N'Huyện', '72');
INSERT INTO quanhuyen VALUES ('709', N'Huyện Hòa Thành', N'Huyện', '72');
INSERT INTO quanhuyen VALUES ('710', N'Huyện Gò Dầu', N'Huyện', '72');
INSERT INTO quanhuyen VALUES ('711', N'Huyện Bến Cầu', N'Huyện', '72');
INSERT INTO quanhuyen VALUES ('712', N'Huyện Trảng Bàng', N'Huyện', '72');
INSERT INTO quanhuyen VALUES ('718', N'Thành phố Thủ Dầu Một', N'Thành phố', '74');
INSERT INTO quanhuyen VALUES ('719', N'Huyện Bàu Bàng', N'Huyện', '74');
INSERT INTO quanhuyen VALUES ('720', N'Huyện Dầu Tiếng', N'Huyện', '74');
INSERT INTO quanhuyen VALUES ('721', N'Thị xã Bến Cát', N'Thị xã', '74');
INSERT INTO quanhuyen VALUES ('722', N'Huyện Phú Giáo', N'Huyện', '74');
INSERT INTO quanhuyen VALUES ('723', N'Thị xã Tân Uyên', N'Thị xã', '74');
INSERT INTO quanhuyen VALUES ('724', N'Thị xã Dĩ An', N'Thị xã', '74');
INSERT INTO quanhuyen VALUES ('725', N'Thị xã Thuận An', N'Thị xã', '74');
INSERT INTO quanhuyen VALUES ('726', N'Huyện Bắc Tân Uyên', N'Huyện', '74');
INSERT INTO quanhuyen VALUES ('731', N'Thành phố Biên Hòa', N'Thành phố', '75');
INSERT INTO quanhuyen VALUES ('732', N'Thị xã Long Khánh', N'Thị xã', '75');
INSERT INTO quanhuyen VALUES ('734', N'Huyện Tân Phú', N'Huyện', '75');
INSERT INTO quanhuyen VALUES ('735', N'Huyện Vĩnh Cửu', N'Huyện', '75');
INSERT INTO quanhuyen VALUES ('736', N'Huyện Định Quán', N'Huyện', '75');
INSERT INTO quanhuyen VALUES ('737', N'Huyện Trảng Bom', N'Huyện', '75');
INSERT INTO quanhuyen VALUES ('738', N'Huyện Thống Nhất', N'Huyện', '75');
INSERT INTO quanhuyen VALUES ('739', N'Huyện Cẩm Mỹ', N'Huyện', '75');
INSERT INTO quanhuyen VALUES ('740', N'Huyện Long Thành', N'Huyện', '75');
INSERT INTO quanhuyen VALUES ('741', N'Huyện Xuân Lộc', N'Huyện', '75');
INSERT INTO quanhuyen VALUES ('742', N'Huyện Nhơn Trạch', N'Huyện', '75');
INSERT INTO quanhuyen VALUES ('747', N'Thành phố Vũng Tàu', N'Thành phố', '77');
INSERT INTO quanhuyen VALUES ('748', N'Thành phố Bà Rịa', N'Thành phố', '77');
INSERT INTO quanhuyen VALUES ('750', N'Huyện Châu Đức', N'Huyện', '77');
INSERT INTO quanhuyen VALUES ('751', N'Huyện Xuyên Mộc', N'Huyện', '77');
INSERT INTO quanhuyen VALUES ('752', N'Huyện Long Điền', N'Huyện', '77');
INSERT INTO quanhuyen VALUES ('753', N'Huyện Đất Đỏ', N'Huyện', '77');
INSERT INTO quanhuyen VALUES ('754', N'Huyện Tân Thành', N'Huyện', '77');
INSERT INTO quanhuyen VALUES ('755', N'Huyện Côn Đảo', N'Huyện', '77');
INSERT INTO quanhuyen VALUES ('760', N'Quận 1', N'Quận', '79');
INSERT INTO quanhuyen VALUES ('761', N'Quận 12', N'Quận', '79');
INSERT INTO quanhuyen VALUES ('762', N'Quận Thủ Đức', N'Quận', '79');
INSERT INTO quanhuyen VALUES ('763', N'Quận 9', N'Quận', '79');
INSERT INTO quanhuyen VALUES ('764', N'Quận Gò Vấp', N'Quận', '79');
INSERT INTO quanhuyen VALUES ('765', N'Quận Bình Thạnh', N'Quận', '79');
INSERT INTO quanhuyen VALUES ('766', N'Quận Tân Bình', N'Quận', '79');
INSERT INTO quanhuyen VALUES ('767', N'Quận Tân Phú', N'Quận', '79');
INSERT INTO quanhuyen VALUES ('768', N'Quận Phú Nhuận', N'Quận', '79');
INSERT INTO quanhuyen VALUES ('769', N'Quận 2', N'Quận', '79');
INSERT INTO quanhuyen VALUES ('770', N'Quận 3', N'Quận', '79');
INSERT INTO quanhuyen VALUES ('771', N'Quận 10', N'Quận', '79');
INSERT INTO quanhuyen VALUES ('772', N'Quận 11', N'Quận', '79');
INSERT INTO quanhuyen VALUES ('773', N'Quận 4', N'Quận', '79');
INSERT INTO quanhuyen VALUES ('774', N'Quận 5', N'Quận', '79');
INSERT INTO quanhuyen VALUES ('775', N'Quận 6', N'Quận', '79');
INSERT INTO quanhuyen VALUES ('776', N'Quận 8', N'Quận', '79');
INSERT INTO quanhuyen VALUES ('777', N'Quận Bình Tân', N'Quận', '79');
INSERT INTO quanhuyen VALUES ('778', N'Quận 7', N'Quận', '79');
INSERT INTO quanhuyen VALUES ('783', N'Huyện Củ Chi', N'Huyện', '79');
INSERT INTO quanhuyen VALUES ('784', N'Huyện Hóc Môn', N'Huyện', '79');
INSERT INTO quanhuyen VALUES ('785', N'Huyện Bình Chánh', N'Huyện', '79');
INSERT INTO quanhuyen VALUES ('786', N'Huyện Nhà Bè', N'Huyện', '79');
INSERT INTO quanhuyen VALUES ('787', N'Huyện Cần Giờ', N'Huyện', '79');
INSERT INTO quanhuyen VALUES ('794', N'Thành phố Tân An', N'Thành phố', '80');
INSERT INTO quanhuyen VALUES ('795', N'Thị xã Kiến Tường', N'Thị xã', '80');
INSERT INTO quanhuyen VALUES ('796', N'Huyện Tân Hưng', N'Huyện', '80');
INSERT INTO quanhuyen VALUES ('797', N'Huyện Vĩnh Hưng', N'Huyện', '80');
INSERT INTO quanhuyen VALUES ('798', N'Huyện Mộc Hóa', N'Huyện', '80');
INSERT INTO quanhuyen VALUES ('799', N'Huyện Tân Thạnh', N'Huyện', '80');
INSERT INTO quanhuyen VALUES ('800', N'Huyện Thạnh Hóa', N'Huyện', '80');
INSERT INTO quanhuyen VALUES ('801', N'Huyện Đức Huệ', N'Huyện', '80');
INSERT INTO quanhuyen VALUES ('802', N'Huyện Đức Hòa', N'Huyện', '80');
INSERT INTO quanhuyen VALUES ('803', N'Huyện Bến Lức', N'Huyện', '80');
INSERT INTO quanhuyen VALUES ('804', N'Huyện Thủ Thừa', N'Huyện', '80');
INSERT INTO quanhuyen VALUES ('805', N'Huyện Tân Trụ', N'Huyện', '80');
INSERT INTO quanhuyen VALUES ('806', N'Huyện Cần Đước', N'Huyện', '80');
INSERT INTO quanhuyen VALUES ('807', N'Huyện Cần Giuộc', N'Huyện', '80');
INSERT INTO quanhuyen VALUES ('808', N'Huyện Châu Thành', N'Huyện', '80');
INSERT INTO quanhuyen VALUES ('815', N'Thành phố Mỹ Tho', N'Thành phố', '82');
INSERT INTO quanhuyen VALUES ('816', N'Thị xã Gò Công', N'Thị xã', '82');
INSERT INTO quanhuyen VALUES ('817', N'Thị xã Cai Lậy', N'Huyện', '82');
INSERT INTO quanhuyen VALUES ('818', N'Huyện Tân Phước', N'Huyện', '82');
INSERT INTO quanhuyen VALUES ('819', N'Huyện Cái Bè', N'Huyện', '82');
INSERT INTO quanhuyen VALUES ('820', N'Huyện Cai Lậy', N'Thị xã', '82');
INSERT INTO quanhuyen VALUES ('821', N'Huyện Châu Thành', N'Huyện', '82');
INSERT INTO quanhuyen VALUES ('822', N'Huyện Chợ Gạo', N'Huyện', '82');
INSERT INTO quanhuyen VALUES ('823', N'Huyện Gò Công Tây', N'Huyện', '82');
INSERT INTO quanhuyen VALUES ('824', N'Huyện Gò Công Đông', N'Huyện', '82');
INSERT INTO quanhuyen VALUES ('825', N'Huyện Tân Phú Đông', N'Huyện', '82');
INSERT INTO quanhuyen VALUES ('829', N'Thành phố Bến Tre', N'Thành phố', '83');
INSERT INTO quanhuyen VALUES ('831', N'Huyện Châu Thành', N'Huyện', '83');
INSERT INTO quanhuyen VALUES ('832', N'Huyện Chợ Lách', N'Huyện', '83');
INSERT INTO quanhuyen VALUES ('833', N'Huyện Mỏ Cày Nam', N'Huyện', '83');
INSERT INTO quanhuyen VALUES ('834', N'Huyện Giồng Trôm', N'Huyện', '83');
INSERT INTO quanhuyen VALUES ('835', N'Huyện Bình Đại', N'Huyện', '83');
INSERT INTO quanhuyen VALUES ('836', N'Huyện Ba Tri', N'Huyện', '83');
INSERT INTO quanhuyen VALUES ('837', N'Huyện Thạnh Phú', N'Huyện', '83');
INSERT INTO quanhuyen VALUES ('838', N'Huyện Mỏ Cày Bắc', N'Huyện', '83');
INSERT INTO quanhuyen VALUES ('842', N'Thành phố Trà Vinh', N'Thành phố', '84');
INSERT INTO quanhuyen VALUES ('844', N'Huyện Càng Long', N'Huyện', '84');
INSERT INTO quanhuyen VALUES ('845', N'Huyện Cầu Kè', N'Huyện', '84');
INSERT INTO quanhuyen VALUES ('846', N'Huyện Tiểu Cần', N'Huyện', '84');
INSERT INTO quanhuyen VALUES ('847', N'Huyện Châu Thành', N'Huyện', '84');
INSERT INTO quanhuyen VALUES ('848', N'Huyện Cầu Ngang', N'Huyện', '84');
INSERT INTO quanhuyen VALUES ('849', N'Huyện Trà Cú', N'Huyện', '84');
INSERT INTO quanhuyen VALUES ('850', N'Huyện Duyên Hải', N'Huyện', '84');
INSERT INTO quanhuyen VALUES ('851', N'Thị xã Duyên Hải', N'Thị xã', '84');
INSERT INTO quanhuyen VALUES ('855', N'Thành phố Vĩnh Long', N'Thành phố', '86');
INSERT INTO quanhuyen VALUES ('857', N'Huyện Long Hồ', N'Huyện', '86');
INSERT INTO quanhuyen VALUES ('858', N'Huyện Mang Thít', N'Huyện', '86');
INSERT INTO quanhuyen VALUES ('859', N'Huyện  Vũng Liêm', N'Huyện', '86');
INSERT INTO quanhuyen VALUES ('860', N'Huyện Tam Bình', N'Huyện', '86');
INSERT INTO quanhuyen VALUES ('861', N'Thị xã Bình Minh', N'Thị xã', '86');
INSERT INTO quanhuyen VALUES ('862', N'Huyện Trà Ôn', N'Huyện', '86');
INSERT INTO quanhuyen VALUES ('863', N'Huyện Bình Tân', N'Huyện', '86');
INSERT INTO quanhuyen VALUES ('866', N'Thành phố Cao Lãnh', N'Thành phố', '87');
INSERT INTO quanhuyen VALUES ('867', N'Thành phố Sa Đéc', N'Thành phố', '87');
INSERT INTO quanhuyen VALUES ('868', N'Thị xã Hồng Ngự', N'Thị xã', '87');
INSERT INTO quanhuyen VALUES ('869', N'Huyện Tân Hồng', N'Huyện', '87');
INSERT INTO quanhuyen VALUES ('870', N'Huyện Hồng Ngự', N'Huyện', '87');
INSERT INTO quanhuyen VALUES ('871', N'Huyện Tam Nông', N'Huyện', '87');
INSERT INTO quanhuyen VALUES ('872', N'Huyện Tháp Mười', N'Huyện', '87');
INSERT INTO quanhuyen VALUES ('873', N'Huyện Cao Lãnh', N'Huyện', '87');
INSERT INTO quanhuyen VALUES ('874', N'Huyện Thanh Bình', N'Huyện', '87');
INSERT INTO quanhuyen VALUES ('875', N'Huyện Lấp Vò', N'Huyện', '87');
INSERT INTO quanhuyen VALUES ('876', N'Huyện Lai Vung', N'Huyện', '87');
INSERT INTO quanhuyen VALUES ('877', N'Huyện Châu Thành', N'Huyện', '87');
INSERT INTO quanhuyen VALUES ('883', N'Thành phố Long Xuyên', N'Thành phố', '89');
INSERT INTO quanhuyen VALUES ('884', N'Thành phố Châu Đốc', N'Thành phố', '89');
INSERT INTO quanhuyen VALUES ('886', N'Huyện An Phú', N'Huyện', '89');
INSERT INTO quanhuyen VALUES ('887', N'Thị xã Tân Châu', N'Thị xã', '89');
INSERT INTO quanhuyen VALUES ('888', N'Huyện Phú Tân', N'Huyện', '89');
INSERT INTO quanhuyen VALUES ('889', N'Huyện Châu Phú', N'Huyện', '89');
INSERT INTO quanhuyen VALUES ('890', N'Huyện Tịnh Biên', N'Huyện', '89');
INSERT INTO quanhuyen VALUES ('891', N'Huyện Tri Tôn', N'Huyện', '89');
INSERT INTO quanhuyen VALUES ('892', N'Huyện Châu Thành', N'Huyện', '89');
INSERT INTO quanhuyen VALUES ('893', N'Huyện Chợ Mới', N'Huyện', '89');
INSERT INTO quanhuyen VALUES ('894', N'Huyện Thoại Sơn', N'Huyện', '89');
INSERT INTO quanhuyen VALUES ('899', N'Thành phố Rạch Giá', N'Thành phố', '91');
INSERT INTO quanhuyen VALUES ('900', N'Thị xã Hà Tiên', N'Thị xã', '91');
INSERT INTO quanhuyen VALUES ('902', N'Huyện Kiên Lương', N'Huyện', '91');
INSERT INTO quanhuyen VALUES ('903', N'Huyện Hòn Đất', N'Huyện', '91');
INSERT INTO quanhuyen VALUES ('904', N'Huyện Tân Hiệp', N'Huyện', '91');
INSERT INTO quanhuyen VALUES ('905', N'Huyện Châu Thành', N'Huyện', '91');
INSERT INTO quanhuyen VALUES ('906', N'Huyện Giồng Riềng', N'Huyện', '91');
INSERT INTO quanhuyen VALUES ('907', N'Huyện Gò Quao', N'Huyện', '91');
INSERT INTO quanhuyen VALUES ('908', N'Huyện An Biên', N'Huyện', '91');
INSERT INTO quanhuyen VALUES ('909', N'Huyện An Minh', N'Huyện', '91');
INSERT INTO quanhuyen VALUES ('910', N'Huyện Vĩnh Thuận', N'Huyện', '91');
INSERT INTO quanhuyen VALUES ('911', N'Huyện Phú Quốc', N'Huyện', '91');
INSERT INTO quanhuyen VALUES ('912', N'Huyện Kiên Hải', N'Huyện', '91');
INSERT INTO quanhuyen VALUES ('913', N'Huyện U Minh Thượng', N'Huyện', '91');
INSERT INTO quanhuyen VALUES ('914', N'Huyện Giang Thành', N'Huyện', '91');
INSERT INTO quanhuyen VALUES ('916', N'Quận Ninh Kiều', N'Quận', '92');
INSERT INTO quanhuyen VALUES ('917', N'Quận Ô Môn', N'Quận', '92');
INSERT INTO quanhuyen VALUES ('918', N'Quận Bình Thuỷ', N'Quận', '92');
INSERT INTO quanhuyen VALUES ('919', N'Quận Cái Răng', N'Quận', '92');
INSERT INTO quanhuyen VALUES ('923', N'Quận Thốt Nốt', N'Quận', '92');
INSERT INTO quanhuyen VALUES ('924', N'Huyện Vĩnh Thạnh', N'Huyện', '92');
INSERT INTO quanhuyen VALUES ('925', N'Huyện Cờ Đỏ', N'Huyện', '92');
INSERT INTO quanhuyen VALUES ('926', N'Huyện Phong Điền', N'Huyện', '92');
INSERT INTO quanhuyen VALUES ('927', N'Huyện Thới Lai', N'Huyện', '92');
INSERT INTO quanhuyen VALUES ('930', N'Thành phố Vị Thanh', N'Thành phố', '93');
INSERT INTO quanhuyen VALUES ('931', N'Thị xã Ngã Bảy', N'Thị xã', '93');
INSERT INTO quanhuyen VALUES ('932', N'Huyện Châu Thành A', N'Huyện', '93');
INSERT INTO quanhuyen VALUES ('933', N'Huyện Châu Thành', N'Huyện', '93');
INSERT INTO quanhuyen VALUES ('934', N'Huyện Phụng Hiệp', N'Huyện', '93');
INSERT INTO quanhuyen VALUES ('935', N'Huyện Vị Thuỷ', N'Huyện', '93');
INSERT INTO quanhuyen VALUES ('936', N'Huyện Long Mỹ', N'Huyện', '93');
INSERT INTO quanhuyen VALUES ('937', N'Thị xã Long Mỹ', N'Thị xã', '93');
INSERT INTO quanhuyen VALUES ('941', N'Thành phố Sóc Trăng', N'Thành phố', '94');
INSERT INTO quanhuyen VALUES ('942', N'Huyện Châu Thành', N'Huyện', '94');
INSERT INTO quanhuyen VALUES ('943', N'Huyện Kế Sách', N'Huyện', '94');
INSERT INTO quanhuyen VALUES ('944', N'Huyện Mỹ Tú', N'Huyện', '94');
INSERT INTO quanhuyen VALUES ('945', N'Huyện Cù Lao Dung', N'Huyện', '94');
INSERT INTO quanhuyen VALUES ('946', N'Huyện Long Phú', N'Huyện', '94');
INSERT INTO quanhuyen VALUES ('947', N'Huyện Mỹ Xuyên', N'Huyện', '94');
INSERT INTO quanhuyen VALUES ('948', N'Thị xã Ngã Năm', N'Thị xã', '94');
INSERT INTO quanhuyen VALUES ('949', N'Huyện Thạnh Trị', N'Huyện', '94');
INSERT INTO quanhuyen VALUES ('950', N'Thị xã Vĩnh Châu', N'Thị xã', '94');
INSERT INTO quanhuyen VALUES ('951', N'Huyện Trần Đề', N'Huyện', '94');
INSERT INTO quanhuyen VALUES ('954', N'Thành phố Bạc Liêu', N'Thành phố', '95');
INSERT INTO quanhuyen VALUES ('956', N'Huyện Hồng Dân', N'Huyện', '95');
INSERT INTO quanhuyen VALUES ('957', N'Huyện Phước Long', N'Huyện', '95');
INSERT INTO quanhuyen VALUES ('958', N'Huyện Vĩnh Lợi', N'Huyện', '95');
INSERT INTO quanhuyen VALUES ('959', N'Thị xã Giá Rai', N'Thị xã', '95');
INSERT INTO quanhuyen VALUES ('960', N'Huyện Đông Hải', N'Huyện', '95');
INSERT INTO quanhuyen VALUES ('961', N'Huyện Hoà Bình', N'Huyện', '95');
INSERT INTO quanhuyen VALUES ('964', N'Thành phố Cà Mau', N'Thành phố', '96');
INSERT INTO quanhuyen VALUES ('966', N'Huyện U Minh', N'Huyện', '96');
INSERT INTO quanhuyen VALUES ('967', N'Huyện Thới Bình', N'Huyện', '96');
INSERT INTO quanhuyen VALUES ('968', N'Huyện Trần Văn Thời', N'Huyện', '96');
INSERT INTO quanhuyen VALUES ('969', N'Huyện Cái Nước', N'Huyện', '96');
INSERT INTO quanhuyen VALUES ('970', N'Huyện Đầm Dơi', N'Huyện', '96');
INSERT INTO quanhuyen VALUES ('971', N'Huyện Năm Căn', N'Huyện', '96');
INSERT INTO quanhuyen VALUES ('972', N'Huyện Phú Tân', N'Huyện', '96');
INSERT INTO quanhuyen VALUES ('973', N'Huyện Nọc Hiển',N'Huyện', '96');